server:
  port: 8092
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://${EB_DB_HOST}:${EB_DB_PORT}/${EB_DB}
    username: ${EB_DB_USERNAME}
    password: ${EB_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      dll-auto: none
      show: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    url: jdbc:postgresql://${EB_DB_HOST}:${EB_DB_PORT}/${EB_DB}
    user: ${EB_DB_USERNAME}
    password: ${EB_DB_PASSWORD}
    schemas: core
    locations: classpath:db/migration

check-user-scopes: false

app:
  security:
    jwt:
      keystore-location: ${KEYSTORE_LOCATION}
      keystore-password: ${KEYSTORE_PASSWORD}
      key-alias: ${KEY_ALIAS}